#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source Dependencies/ReleaseTools/Scripts/make-tools

echo "***************"
echo "Releasing macOS"
echo "***************"

rt set scheme ActionStatus-macOS --platform macOS
rt archive --show-output 2> /dev/null | xcpretty
rt export --distribution true
rt notarize
rt wait
rt compress
rt publish
