#!/bin/sh

if [[ ! -e .bin/rt ]]
then
    echo "Rebuilding release tools."
    set -e
    swift build --package-path Dependencies/ReleaseTools --configuration release
    cp Dependencies/ReleaseTools/.build/release/rt .bin/rt
fi

echo "Using release tools $(rt --version)."
