#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source Dependencies/ReleaseTools/Scripts/make-tools

echo " "
echo "**************"
echo "Uploading tvOS"
echo "**************"

rt set scheme ActionStatus-tvOS --platform=tvOS
rt archive --platform=tvOS --show-output 2> /dev/null | xcpretty
rt export --platform=tvOS
rt upload --platform=tvOS
