#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source "bootstrap-tools"

echo "***************"
echo "Releasing macOS"
echo "***************"

set -o pipefail

$RT set scheme ActionStatus-Sparkle --platform macOS
$RT archive --xcconfig Sources/ActionStatus/Resources/IncludeSparkle.xcconfig 2>/dev/null | xcpretty
$RT export --distribution
$RT notarize
$RT wait
$RT compress
$RT publish
