#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source Dependencies/ReleaseTools/Scripts/make-tools

echo "***************"
echo "Releasing macOS"
echo "***************"

set -o pipefail

rt set scheme ActionStatus-Sparkle --platform macOS
rt archive --xcconfig Sources/ActionStatus/Resources/IncludeSparkle.xcconfig 2>/dev/null | xcpretty
rt export --distribution true
rt notarize
rt wait
rt compress
rt publish
