#!/bin/bash
# Purpose: Submit tvOS build using ReleaseTools and push tags.
# Usage: Extras/Scripts/upload-tvOS

set -euo pipefail

echo " "
echo "***************"
echo "Submitting tvOS"
echo "***************"
rt submit --platform=tvOS --scheme=ActionStatus-tvOS
git push --tags --force
