#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source Dependencies/ReleaseTools/Scripts/make-tools

echo " "
echo "***************"
echo "Uploading macOS"
echo "***************"

set -o pipefail

rt set scheme ActionStatus --platform macOS
rt archive --show-output 2> /dev/null | xcpretty
rt export --platform=macOS
rt upload --platform=macOS
