#!/bin/bash
# Purpose: Submit macOS build using ReleaseTools and push tags.
# Usage: Extras/Scripts/upload-macOS

set -euo pipefail

echo " "
echo "****************"
echo "Submitting macOS"
echo "****************"
rt submit --platform=macOS --scheme=ActionStatus
git push --tags --force
