#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source "bootstrap-tools"

echo " "
echo "***************"
echo "Uploading macOS"
echo "***************"

$RT set scheme ActionStatus --platform macOS
$RT archive --show-output 2> /dev/null | xcpretty
$RT export --platform=macOS
$RT upload --platform=macOS
