#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source "bootstrap-tools"

echo " "
echo "**************"
echo "Uploading tvOS"
echo "**************"

$RT set scheme ActionStatus-tvOS --platform=tvOS
$RT archive --platform=tvOS --show-output 2> /dev/null | xcpretty
$RT export --platform=tvOS
$RT upload --platform=tvOS
