#!/bin/bash
# Purpose: Submit iOS build using ReleaseTools and push tags.
# Usage: Extras/Scripts/upload-iOS

set -euo pipefail

echo " "
echo "**************"
echo "Submitting iOS"
echo "**************"
rt submit --platform=iOS --scheme=ActionStatus
git push --tags --force
